// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contracts/{address}": {
            "get": {
                "description": "Get a cached smart contract from the database by its address and network",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Get contract from database",
                "parameters": [
                    {
                        "maxLength": 42,
                        "minLength": 42,
                        "type": "string",
                        "description": "Contract Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "ethereum",
                            "polygon",
                            "bsc",
                            "base",
                            "arbitrum",
                            "avalanche",
                            "optimism",
                            "gnosis",
                            "fantom",
                            "celo"
                        ],
                        "type": "string",
                        "default": "ethereum",
                        "description": "Network Name",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/contracts/{address}/source-code": {
            "get": {
                "description": "Get the source code of a smart contract from Etherscan by its address and save it to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Fetch contract source code",
                "parameters": [
                    {
                        "maxLength": 42,
                        "minLength": 42,
                        "type": "string",
                        "description": "Contract Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "ethereum",
                            "polygon",
                            "bsc",
                            "base",
                            "arbitrum",
                            "avalanche",
                            "optimism",
                            "gnosis",
                            "fantom",
                            "celo"
                        ],
                        "type": "string",
                        "default": "ethereum",
                        "description": "Network Name",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/dynamic-analysis": {
            "post": {
                "description": "Performs dynamic security analysis on Solidity source code using AI/LLM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dynamic-analysis"
                ],
                "summary": "Analyze Solidity contract using AI for security vulnerabilities",
                "parameters": [
                    {
                        "description": "Contract source code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analysis.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/static-analysis": {
            "post": {
                "description": "Performs static security analysis on Solidity source code using Slither",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "static-analysis"
                ],
                "summary": "Analyze Solidity contract for security vulnerabilities",
                "parameters": [
                    {
                        "description": "Contract source code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analysis.AnalyzeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "analysis.AnalyzeRequest": {
            "type": "object",
            "required": [
                "source_code"
            ],
            "properties": {
                "source_code": {
                    "type": "string",
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Slyther Go Backend API",
	Description:      "This is a server for Slyther Go Backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
